# Generated by Django 5.2.4 on 2025-07-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name des Unternehmens')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Webseite')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Branche')),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='application_app.company', verbose_name='Unternehmen')),
            ],
            options={
                'verbose_name': 'Kontaktperson',
                'verbose_name_plural': 'Kontaktpersonen',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Jobtitel')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('APPLIED', 'Beworben'), ('INTERVIEW', 'Interview'), ('OFFER', 'Angebot erhalten'), ('REJECTED', 'Abgelehnt'), ('WITHDRAWN', 'Zurückgezogen')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('applied_on', models.DateField(blank=True, null=True, verbose_name='Beworben am')),
                ('follow_up_on', models.DateField(blank=True, help_text='Datum für die Wiedervorlage/Nachverfolgung', null=True, verbose_name='Wiedervorlage am')),
                ('job_posting_link', models.URLField(blank=True, verbose_name='Link zur Ausschreibung')),
                ('salary_expectation', models.PositiveIntegerField(blank=True, help_text='Jährliche Gehaltsvorstellung in EUR', null=True, verbose_name='Gehaltsvorstellung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application_app.company', verbose_name='Unternehmen')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application_app.contact', verbose_name='Kontaktperson')),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Notiztext')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application_app.application', verbose_name='Bewerbung')),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['-created_at'],
            },
        ),
    ]
