# Generated by Django 5.2.4 on 2025-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0002_company_user_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_on',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Interview am'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_on',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Angebot erhalten am'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_on',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Absage erhalten am'),
        ),
    ]
