# Generated by Django 5.2.4 on 2025-08-11 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0003_application_interview_on_application_offer_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_on',
            field=models.DateField(blank=True, null=True, verbose_name='Interview am'),
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_on',
            field=models.DateField(blank=True, null=True, verbose_name='Angebot erhalten am'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejected_on',
            field=models.DateField(blank=True, null=True, verbose_name='Absage erhalten am'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name des Unternehmens'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('user', 'name')},
        ),
    ]
